const BAD_REQUEST_STATUS_CODE = 400;

const INTERNAL_SERVER_ERROR = 500;

const NOT_FOUND_ERROR = 404;

const CONFLICT_ERROR = 409;

const UNAUTHORIZED_ERROR_CODE = 401;

const NOT_CORRECT_USER_CODE = 403;

module.exports = {
  BAD_REQUEST_STATUS_CODE,
  INTERNAL_SERVER_ERROR,
  NOT_FOUND_ERROR,
  CONFLICT_ERROR,
  UNAUTHORIZED_ERROR_CODE,
  NOT_CORRECT_USER_CODE,
};
